
spring:
  datasource:
    url: jdbc:sqlserver://10.184.1.17:1433;databaseName=enterprise_std
    username: sxdev
    password: DevDB2016
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
          initial-size: 1
          min-idle: 1
          max-active: 10
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 20
          use-global-data-source-stat: true
          stat-view-servlet:
            enabled: true
            login-username: xxx
            login-password: xxx
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 20Mb
mybatis:
  type-aliases-package: com.chinalife.enterprise.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true


base64Security: ErIDEspI

server:
  port: 8086

photoPath: E:/EnterpriseUploadPic/
downLoadPath: http://10.20.112.57/EnterpriseUploadPic/
temporaryPath: D:/download/
WxAppId: wx6ad194cb132c72b6
WxAppSecret: cd1c8b04c9a7c196771529fc003833e1

